---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vox.vox.io
  resources:
  - evalruns
  - inferencepipelines
  - voicemodels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vox.vox.io
  resources:
  - evalruns/finalizers
  - inferencepipelines/finalizers
  - voicemodels/finalizers
  verbs:
  - update
- apiGroups:
  - vox.vox.io
  resources:
  - evalruns/status
  - inferencepipelines/status
  - voicemodels/status
  verbs:
  - get
  - patch
  - update
